### ISSUE TITLE
Parse error: syntax error

### ISSUE THREAD

**Issue by CEHA** [ajm113/OpenTor-X#1]
Parse error: syntax error, unexpected end of file in C:\Xampp\htdocs\opentorx\application\views\default\table.php on line 70

Cant start on "xampp-win32-5.5.19-0-VC11"

**Comment by ajm113** [comment]
I'll be looking into it today. Sorry for the delay. For some reason I didn't get notified of this issue.

Plus I've been meaning to make updates to this project now that KAT is no longer running.

**Comment by ajm113** [comment]
From some research sounds like you have to turn on short tags in PHP inside the php.ini. The project by default (master) is extremely short tag happy. I've fixed this inside the development branch here: https://github.com/ajm113/OpenTor-X/commit/03da480b02c90713e60686cf11aba8b7bc862a7e#diff-389b97eae021ef9d0c30c70666c5438cL8

I'm hopping I can update a stable version of this project today or sometime this week.

**Comment by ajm113** [comment]
I'm going to close this issue, since the new release should resolve this. Open a new issue if the same thing continues. #2
