### ISSUE TITLE
Add new sites to index

### ISSUE THREAD

**Issue by leporno** [ajm113/OpenTor-X#4]
Hi, installed script, but how to add new torrent sites to index? There is no information in readme. Thanks

**Comment by ajm113** [comment]
> but how to add new torrent sites to index

This doesn't have a crawler if that's what you are asking. You must write a script yourself that crawls torrent sites to add to the database. You can easily write one yourself or use a prewritten one to that grabs key information you need to insert into the database. This is just a skeleton platform that hosts and displays data to the user.

Let me know if that helps.
